### ISSUE TITLE
SES Email Composer places all destination types on the 'TO' line

### ISSUE THREAD

**Issue by mvelez-nydig** [micronaut-projects/micronaut-email#119]
### Expected Behavior

The `destinationBuilder` method in [SesEmailComposer](https://github.com/micronaut-projects/micronaut-email/blob/master/email-amazon-ses/src/main/java/io/micronaut/email/ses/SesEmailComposer.java) should populate the `toAddresses`, `ccAddresses` and `bccAddresses` on their respective lines.
e.g.:
```java
if (email.getTo() != null) {
      destinationBuilder.toAddresses(email.getTo().stream().map(Contact::getEmail).collect(Collectors.toList()));
}
if (email.getCc() != null) {
      destinationBuilder.ccAddresses(email.getCc().stream().map(Contact::getEmail).collect(Collectors.toList()));
}
if (email.getBcc() != null) {
      destinationBuilder.bccAddresses(email.getBcc().stream().map(Contact::getEmail).collect(Collectors.toList()));
}
```

### Actual Behaviour

The `destinationBuilder` method is currently placing every destination type on the `TO` line, meaning that CC and BCC lists will also show up there. 

This is what the method looks like right now:
```java
@NonNull
private Destination.Builder destinationBuilder(@NonNull Email email) {
      Destination.Builder destinationBuilder = Destination.builder();
      if (email.getTo() != null) {
          destinationBuilder.toAddresses(email.getTo().stream().map(Contact::getEmail).collect(Collectors.toList()));
      }
      if (email.getCc() != null) {
          destinationBuilder.toAddresses(email.getCc().stream().map(Contact::getEmail).collect(Collectors.toList()));
      }
      if (email.getBcc() != null) {
          destinationBuilder.toAddresses(email.getBcc().stream().map(Contact::getEmail).collect(Collectors.toList()));
      }
      return destinationBuilder;
}
```
This will also replace the `toAddresses` destination in each step if CC and BCC are present. So in this case, the `to:` line will only contain the BCC addresses.

### Steps To Reproduce

Create an email client project with `io.micronaut.email:micronaut-email-amazon-ses` as a dependency.

When composing the message, create an `Email.Builder` object with their respective destination field like this:

```kotlin
val builder = Email.builder()
            .from(Contact("from@test.com"))
            .replyTo(Contact("replyTo@test.com"))
            .to(listOf(Contact("to@test.com")))
            .cc(listOf(Contact("cc@test.com")))
            .bcc(listOf(Contact("bcc@test.com")))
            .subject("fooBar")
            .body(
                MultipartBody("html", "text")
            )
```
Use your client to send an email, and when you receive the message in your inbox, you will see that the `to:` line will contain `bcc@test.com` instead of `to@test.com`, and the `cc:` and `bcc:` lines will be empty.

### Environment Information

-Operating System: MacOS Big Sur
-JDK 17
-Kotlin 1.6.21
-Micronaut 3.6.1
-Micronaut Email 1.3.1

### Version

3.6.1

**Comment by graemerocher** [comment]
seems like a simple fix, would you like to send a PR?

**Comment by mvelez-nydig** [comment]
> 

For sure, I'm sending a PR shortly
