### ISSUE TITLE
How to set the "from" name when sending email with Micronaut Email?

### ISSUE THREAD

**Issue by nurulratifainah** [micronaut-projects/micronaut-email#315]
### Issue description

I'm currently working on a project using Micronaut Email, and I'm trying to customize the "from" name when sending emails. I've been able to set the sender's email address, but I'm not sure how to change the "from" name that is displayed in the recipient's inbox.

I've searched through the documentation and couldn't find a clear example or explanation on how to achieve this. Can someone please provide guidance or an example of how to set a custom "from" name when sending an email with Micronaut Email?

Any help or code snippets would be greatly appreciated. Thank you in advance for your assistance!

**Comment by sdelamo** [comment]
See: https://micronaut-projects.github.io/micronaut-email/latest/guide/configurationreference.html#io.micronaut.email.configuration.FromConfigurationProperties

- `micronaut.email.from.name` The name of the contact sending the email.
