### ISSUE TITLE
Support for custom headers

### ISSUE THREAD

**Issue by lpellegr** [micronaut-projects/micronaut-email#35]
### Feature description

Amazon SES, Postmark and other allow passing custom headers as a convenient solution to add context when handling notification events related to the dispatch of emails on their platform. 

Unfortunately, micronaut-email seems not supporting the addition of headers to emails. This is a feature request.

**Comment by sdelamo** [comment]
We support that. You can use the send method which takes a consumer argument

https://github.com/micronaut-projects/micronaut-email/blob/master/email/src/main/java/io/micronaut/email/EmailSender.java#L50

```java
emailSender.send(builder, request -> {
//Set any headers. 
})```

Le me know if it helps.
